# SPDX-FileCopyrightText: 2026 hc contributors
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Thin Python facade over the bundled `hc_execution_engine` nanobind
# extension. The extension lives under ``hc/_native/python_packages/``
# (a parallel layout to ``hc_front``); we prepend that directory to
# ``sys.path`` lazily so importing ``hc.execution_engine`` doesn't pay
# the cost on plain ``import hc``.

from __future__ import annotations

import sys
from typing import TYPE_CHECKING, Protocol

from ._native_paths import package_native_root

_PYTHON_PACKAGES_DIR = package_native_root() / "python_packages"


def _ensure_runtime_on_path() -> None:
    entry = str(_PYTHON_PACKAGES_DIR)
    if entry not in sys.path:
        sys.path.insert(0, entry)


def _load_extension() -> object:
    _ensure_runtime_on_path()
    try:
        # The package is generated by the native build under
        # `hc/_native/python_packages/hc_runtime/`; mypy can't see it
        # statically and there's no useful place for a stub.
        import hc_runtime.hc_execution_engine as ext  # type: ignore[import-not-found]
    except ImportError as exc:
        raise ImportError(
            "hc.execution_engine: bundled native module is missing.\n"
            f"expected at {_PYTHON_PACKAGES_DIR / 'hc_runtime'}.\n"
            "Reinstall hc (the build copies the .so under hc/_native/) or "
            "run `python -m build_tools.hc_native_tools` from a checkout."
        ) from exc
    return ext


# We rebind `ExecutionEngine` / `ExecutionEngineOptions` lazily on first
# attribute access so ``import hc.execution_engine`` succeeds even when
# the native module is missing — callers see a clean error only when
# they actually try to use the engine.
class _Lazy:
    __slots__ = ("_ext",)

    def __init__(self) -> None:
        self._ext: object | None = None

    def _get(self) -> object:
        if self._ext is None:
            self._ext = _load_extension()
        return self._ext

    def __getattr__(self, name: str) -> object:
        return getattr(self._get(), name)


_LAZY = _Lazy()


# Type stubs so static type checkers and editors see the public surface.
if TYPE_CHECKING:

    class CodeGenOptLevel:
        O0: CodeGenOptLevel
        O1: CodeGenOptLevel
        O2: CodeGenOptLevel
        O3: CodeGenOptLevel

    class ExecutionEngineOptions(Protocol):
        jit_code_gen_opt_level: CodeGenOptLevel | None

        def set_symbol_map(self, symbols: dict[str, int]) -> None: ...

    class ExecutionEngine(Protocol):
        def __init__(self, options: ExecutionEngineOptions) -> None: ...

        def load_llvm_ir(self, text: str) -> int: ...

        def lookup(self, handle: int, name: str) -> int: ...

        def release_module(self, handle: int) -> None: ...


def __getattr__(name: str) -> object:
    if name in {"ExecutionEngine", "ExecutionEngineOptions", "CodeGenOptLevel"}:
        return getattr(_LAZY, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return ["ExecutionEngine", "ExecutionEngineOptions", "CodeGenOptLevel"]


__all__ = ["CodeGenOptLevel", "ExecutionEngine", "ExecutionEngineOptions"]
