# SPDX-FileCopyrightText: 2026 hc contributors
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Facade over the `hc_execution_engine` nanobind extension under
# `hc/_native/python_packages/`. Path prepend is lazy so `import hc`
# stays cheap.

from __future__ import annotations

import sys
from typing import TYPE_CHECKING

from ._native_paths import package_native_root

_PYTHON_PACKAGES_DIR = package_native_root() / "python_packages"


def _ensure_runtime_on_path() -> None:
    entry = str(_PYTHON_PACKAGES_DIR)
    if entry not in sys.path:
        sys.path.insert(0, entry)


def _load_extension() -> object:
    _ensure_runtime_on_path()
    try:
        # Generated by the native build; no static stub.
        import hc_runtime.hc_execution_engine as ext  # type: ignore[import-not-found]
    except ImportError as exc:
        raise ImportError(
            "hc.execution_engine: bundled native module is missing.\n"
            f"expected at {_PYTHON_PACKAGES_DIR / 'hc_runtime'}.\n"
            "Reinstall hc (the build copies the .so under hc/_native/) or "
            "run `python -m build_tools.hc_native_tools` from a checkout."
        ) from exc
    return ext


# Lazy rebind so import succeeds without the native module; error
# fires on actual use.
class _Lazy:
    __slots__ = ("_ext",)

    def __init__(self) -> None:
        self._ext: object | None = None

    def _get(self) -> object:
        if self._ext is None:
            self._ext = _load_extension()
        return self._ext

    def __getattr__(self, name: str) -> object:
        return getattr(self._get(), name)


_LAZY = _Lazy()


# Type stubs for static checkers. Plain classes because callers
# instantiate at runtime; `Protocol` would reject construction.
if TYPE_CHECKING:

    class CodeGenOptLevel:
        O0: CodeGenOptLevel
        O1: CodeGenOptLevel
        O2: CodeGenOptLevel
        O3: CodeGenOptLevel

    class ExecutionEngineOptions:
        jit_code_gen_opt_level: CodeGenOptLevel | None

        def __init__(self) -> None: ...

        def set_symbol_map(self, symbols: dict[str, int]) -> None: ...

    class ExecutionEngine:
        def __init__(self, options: ExecutionEngineOptions) -> None: ...

        def load_llvm_ir(self, text: str) -> int: ...

        def load_mlir(self, text: str) -> int: ...

        def lookup(self, handle: int, name: str) -> int: ...

        def release_module(self, handle: int) -> None: ...


def __getattr__(name: str) -> object:
    if name in {"ExecutionEngine", "ExecutionEngineOptions", "CodeGenOptLevel"}:
        return getattr(_LAZY, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return ["ExecutionEngine", "ExecutionEngineOptions", "CodeGenOptLevel"]


__all__ = ["CodeGenOptLevel", "ExecutionEngine", "ExecutionEngineOptions"]
