// SPDX-FileCopyrightText: 2026 hc contributors
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef HC_TRANSFORMS_PASSES_H
#define HC_TRANSFORMS_PASSES_H

#include "mlir/Pass/Pass.h"

#include <memory>

namespace mlir::hc {

// ODS-generated pass-base declarations plus the `createXxxPass()`
// factories (one per pass in `Passes.td`). With no `let constructor`
// in `Passes.td`, tablegen emits each factory as a friend of its
// CRTP base so the DerivedT is the one we `std::make_unique<>` here
// — see `Passes.td` for the per-pass contracts.
#define GEN_PASS_DECL
#include "hc/Transforms/Passes.h.inc"

// `registerHCTransformsPasses()` — generated by tablegen from
// `Passes.td`; registers every pass declared there with the global
// `mlir-opt`-style registry.
#define GEN_PASS_REGISTRATION
#include "hc/Transforms/Passes.h.inc"

} // namespace mlir::hc

#endif // HC_TRANSFORMS_PASSES_H
