// SPDX-FileCopyrightText: 2026 hc contributors
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef HC_CONVERSION_HCFRONTTOHC_HCFRONTTOHC_H
#define HC_CONVERSION_HCFRONTTOHC_HCFRONTTOHC_H

#include "mlir/Pass/Pass.h"

#include <memory>

namespace mlir::hc::front {

// The mechanical `hc_front` -> `hc` lowering. Walks a module of
// `hc_front.kernel` / `hc_front.func` / `hc_front.intrinsic` ops and emits
// the parallel `hc` callables in place. Types are emitted as `!hc.undef`
// (except where annotations on parameters let us pin something stricter);
// a later inference pass narrows them.
std::unique_ptr<Pass> createConvertHCFrontToHCPass();

// Forward declarations for the ODS-generated pass bases.
#define GEN_PASS_DECL
#include "hc/Conversion/HCFrontToHC/Passes.h.inc"

// `registerHCFrontToHCConversionPasses()` — generated by tablegen from
// `Passes.td`; registers `-convert-hc-front-to-hc` with the global
// `mlir-opt`-style registry.
#define GEN_PASS_REGISTRATION
#include "hc/Conversion/HCFrontToHC/Passes.h.inc"

} // namespace mlir::hc::front

#endif // HC_CONVERSION_HCFRONTTOHC_HCFRONTTOHC_H
