// SPDX-FileCopyrightText: 2026 hc contributors
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef HC_CONVERSION_HCFRONTTOHC_HCFRONTTOHC_H
#define HC_CONVERSION_HCFRONTTOHC_HCFRONTTOHC_H

#include "mlir/Pass/Pass.h"

#include <memory>

namespace mlir::hc::front {

// `-convert-hc-front-to-hc`: lowers `hc_front` Python-shaped ops
// (kernels, funcs, name-store placeholders, region carriers) to
// their `hc`-dialect counterparts — the first concrete IR step off
// the AST.
//
// ODS-generated pass-base declarations plus the
// `createConvertHCFrontToHCPass()` factory. With no `let constructor` in
// `Passes.td`, tablegen emits the factory as a friend of the CRTP base so the
// DerivedT is the one we `std::make_unique<>` here — see `Passes.td` for the
// pass contract.
#define GEN_PASS_DECL
#include "hc/Conversion/HCFrontToHC/Passes.h.inc"

// `registerHCFrontToHCConversionPasses()` — generated by tablegen from
// `Passes.td`; registers `-convert-hc-front-to-hc` with the global
// `mlir-opt`-style registry.
#define GEN_PASS_REGISTRATION
#include "hc/Conversion/HCFrontToHC/Passes.h.inc"

} // namespace mlir::hc::front

#endif // HC_CONVERSION_HCFRONTTOHC_HCFRONTTOHC_H
